from Node import *
from Btree import *
import time

if __name__ == '__main__':
    print("TEST1 PY")
    root = Node([], [], None, True)
    arbre = Btree(2, 3, root)
    print("CARACTERISTOQUES DE L'ARBRE : L = "+str(arbre.min_sons)+" U = "+str(arbre.max_sons)+" !")
    time.sleep(1.0)
    l = [2, 4, 5, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 7, 9, 11, 13]
    for i in l:
        print("Insertion de "+str(i)+"")
        arbre.insert(i)
        print("ARBRE")
        arbre.display_tree(arbre.root)
        time.sleep(1.0)
    print("#--------------------PEMIÈRE RECHERCHE DE 42---------------------#")
    bool1 = arbre.btree_search(42)
    print("RÉSULTAT DE LA RECHERCHE :",end=" ")
    print(bool1)
    print()
    print("#--------------------FIN DE LA RECHERCHE DE 42-------------------#")
    print()
    print("#---------------VÉRIFICATION 1 SI C'EST UN ARBRE B---------------#")
    booltree = arbre.est_ArbreB() 
    print("RÉSULTAT DE LA VÉRIFICATION :",end=" ")
    print(booltree)
    print()
    time.sleep(1.0)
    print("#-------------------- FIN DE LA VÉRIFICATION --------------------#")
    print()
    print("#-----------------------INSERTION DE 42--------------------------#") 
    arbre.insert(i)
    print("#--------------------FIN DE L'INSERTION DE 42--------------------#")
    print()
    time.sleep(1.0)
    print("#---------------VÉRIFICATION 2 SI C'EST UN ARBRE B---------------#")
    booltree2 = arbre.est_ArbreB()
    print("RÉSULTAT DE LA VÉRIFICATION :",end=" ")
    print(booltree2)
    print()
    print("#-------------------- FIN DE LA VÉRIFICATION --------------------#")
    print()
    print("#------------------------- ARBRE FINAL --------------------------#")
    print()
    time.sleep(1.0)
    arbre.display_tree(arbre.root)